// ============================================================
//  KOLEKSI TAMBAHAN PERPUSTAKAAN (daftar dari pemilik rumah)
//  - Metadata (pengarang, tahun, penerbit) diverifikasi dari sumber asli.
//  - Isi yang bisa dibaca di dalam game adalah RINGKASAN & ULASAN buatan sendiri,
//    bukan salinan teks asli (kecuali kutipan pendek dari karya domain publik).
//  - Tiap buku menyertakan cara membaca versi lengkapnya secara legal.
// ============================================================
import { SHELVES, BOOKS } from './books.js';

export const ACCESS = {
  ipusnas: { label: 'iPusnas (gratis)', note: 'Aplikasi perpustakaan digital Perpusnas RI — pinjam e-book gratis dengan antrean. Unduh "iPusnas" di Play Store / App Store.' },
  gutenberg: { label: 'Domain publik (gratis)', note: 'Hak ciptanya sudah habis. Bisa diunduh legal & gratis (umumnya terjemahan Inggris) di Project Gutenberg / Standard Ebooks.' },
  store: { label: 'Toko e-book resmi (berbayar)', note: 'Google Play Books, Amazon Kindle, atau Gramedia Digital.' },
  manga: { label: 'Platform manga legal', note: 'Baca lewat layanan resmi seperti VIZ Manga / penerbit lisensi Indonesia (mis. Elex Media, M&C!).' },
  perpus: { label: 'Perpustakaan fisik', note: 'Tersedia di perpustakaan daerah/kampus; cek katalog OPAC setempat.' },
};
const G = (q) => `https://www.gutenberg.org/ebooks/search/?query=${encodeURIComponent(q)}`;

SHELVES.push(
  { id: 'klasik', label: 'Buku Klasik', color: '#6b3a1f' },
  { id: 'manga', label: 'Manga', color: '#b3263e' },
  { id: 'fiksi', label: 'Buku Lain (Fiksi Modern)', color: '#3b3f8f' },
  { id: 'nonfiksi', label: 'Non-fiksi & Sains', color: '#1f6f6a' },
  { id: 'upgrade', label: 'Upgrade Diri', color: '#c27a12' },
  { id: 'ipusnas', label: 'Ada di iPusnas & Perpus', color: '#4d6b2a' },
);

// meta: [pengarang, tahun terbit pertama, penerbit/edisi, genre, akses[], catatan verifikasi?]
const B = (id, shelf, title, meta, p2, p3, extra = {}) => ({ id, shelf, title, author: meta[0], year: meta[1], publisher: meta[2], genre: meta[3], access: meta[4], verify: meta[5] || null, skill: extra.skill || 'logika', link: extra.link || null, pages: [null, p2, p3], ...extra });

const LIST = [
  // ------------------- KLASIK -------------------
  B('k1', 'klasik', 'Crime and Punishment (Kejahatan dan Hukuman)', ['Fyodor Dostoevsky', 1866, 'Terbit berseri di Russky Vestnik; terjemahan Inggris Constance Garnett (1914)', 'Novel psikologis', ['gutenberg', 'ipusnas']],
    'Rodion Raskolnikov, mantan mahasiswa miskin di St. Petersburg, meyakinkan dirinya bahwa manusia "luar biasa" berhak melanggar hukum demi tujuan besar. Setelah melakukan kejahatan berat, ia justru digerogoti demam, paranoia, dan rasa bersalah.',
    'Penyidik Porfiry Petrovich mengejarnya lewat percakapan yang menekan batin, sementara Sonya Marmeladova — perempuan yang hidupnya sangat berat namun penuh kasih — menjadi jalan Raskolnikov menuju pengakuan dan penebusan. Tema: nurani, teori vs kemanusiaan, dan kemungkinan manusia berubah.',
    { link: G('Crime and Punishment Dostoyevsky') }),
  B('k2', 'klasik', 'Botchan', ['Natsume Sōseki', 1906, 'Terbit di majalah Hototogisu; terjemahan Inggris Yasotaro Morri (1918)', 'Novel komedi', ['gutenberg']],
    'Pemuda Tokyo yang blak-blakan, jujur sampai ceroboh, menjadi guru matematika di sekolah menengah di Matsuyama, Shikoku. Ia langsung bentrok dengan murid-murid jahil dan para guru yang penuh intrik — terutama si "Kemeja Merah" yang licik.',
    'Satu-satunya yang benar-benar menyayanginya adalah Kiyo, pengasuh tua di rumahnya dulu. Novel pendek ini lucu sekaligus sindiran tajam terhadap kemunafikan birokrasi; sampai kini termasuk novel paling banyak dibaca di Jepang.',
    { link: G('Botchan Natsume') , skill: 'karisma' }),
  B('k3', 'klasik', 'The Alchemist (Sang Alkemis)', ['Paulo Coelho', 1988, 'Terbit asli O Alquimista (Brasil); edisi Indonesia Gramedia Pustaka Utama', 'Novel fabel/spiritual', ['store', 'ipusnas']],
    'Santiago, gembala muda dari Andalusia, bermimpi berulang tentang harta karun di dekat piramida Mesir. Ia menjual dombanya dan berangkat, bertemu raja Melkisedek, bekerja di toko kristal di Tanger, menyeberangi gurun, lalu berguru pada seorang alkemis.',
    'Intinya soal "Legenda Pribadi" — impian terdalam seseorang — dan keberanian mendengarkan hati. Bukan buku klasik lama (masih dilindungi hak cipta), tetapi sudah jadi klasik modern yang diterjemahkan ke puluhan bahasa.',
    { skill: 'kreatif' }),
  B('k4a', 'klasik', 'Max Havelaar', ['Multatuli (Eduard Douwes Dekker)', 1860, 'Terbit asli di Belanda; banyak terjemahan Indonesia', 'Novel satir/antikolonial', ['gutenberg', 'ipusnas']],
    'Catatan: di daftar tertulis "Prince (Max Havelaar)" — di rak ini kami sediakan dua-duanya. Max Havelaar bercerita tentang asisten residen Lebak yang mencoba melawan penindasan rakyat oleh bupati setempat dan sistem tanam paksa, tetapi justru disingkirkan pemerintah kolonial.',
    'Novel ini disusun berlapis — ada makelar kopi Batavus Droogstoppel yang menyebalkan, ada kisah Saidjah dan Adinda yang tragis. Terbitnya membuka mata publik Eropa tentang kekejaman di Hindia Belanda.',
    { link: G('Max Havelaar Multatuli') }),
  B('k4b', 'klasik', 'The Prince (Sang Pangeran)', ['Niccolò Machiavelli', 1532, 'Ditulis ±1513, terbit anumerta 1532; terjemahan Inggris W. K. Marriott (1908)', 'Filsafat politik', ['gutenberg']],
    'Buku saku kekuasaan: bagaimana penguasa mendapatkan, mempertahankan, dan kehilangan negara. Machiavelli membahas kerajaan warisan dan baru, pasukan sendiri vs tentara bayaran, serta pertanyaan terkenal: lebih baik dicintai atau ditakuti?',
    'Kontroversial karena memisahkan politik dari moral pribadi, sampai melahirkan istilah "machiavellian". Dibaca lebih baik sebagai pengamatan tajam tentang realitas kekuasaan, bukan panduan hidup.',
    { link: G('The Prince Machiavelli') }),
  B('k5', 'klasik', 'Belenggu', ['Armijn Pane', 1940, 'Terbit berseri di Poedjangga Baroe (1940); lalu Dian Rakyat', 'Novel psikologis', ['perpus', 'ipusnas'], 'Di daftar tertulis "Belenggu Ganas"; judul yang terverifikasi adalah "Belenggu".'],
    'Dokter Sukartono (Tono) menikah dengan Sumartini (Tini) karena merasa cocok secara intelektual, bukan karena cinta. Keduanya sibuk dan saling asing, sampai Tono dekat kembali dengan Rohayah (Yah), perempuan dari masa lalunya yang membuatnya merasa tenang.',
    'Sempat ditolak Balai Pustaka, novel ini dianggap novel psikologis pertama Indonesia — memakai monolog batin dan elipsis untuk menampilkan konflik jiwa, serta tarik-menarik antara modernitas dan tradisi.',
    { skill: 'karisma' }),
  B('k6', 'klasik', 'Catatan Seorang Demonstran', ['Soe Hok Gie', 1983, 'LP3ES (terbit anumerta dari buku harian 1959–1969)', 'Buku harian/sejarah', ['ipusnas', 'store']],
    'Kumpulan buku harian Soe Hok Gie sejak remaja hingga menjelang wafatnya di Gunung Semeru pada Desember 1969. Isinya pergolakan mahasiswa UI, demonstrasi 1966, kritik terhadap kekuasaan, persahabatan, dan kecintaannya pada alam.',
    'Gie menulis jujur tentang idealisme dan kesepian seorang yang memilih berpikir bebas. Pernah difilmkan sebagai "Gie" (2005).',
    { skill: 'karisma' }),
  B('k7', 'klasik', 'Kokoro', ['Natsume Sōseki', 1914, 'Terbit berseri di Asahi Shimbun', 'Novel', ['gutenberg', 'store']],
    'Seorang mahasiswa muda berteman dengan pria misterius yang ia panggil "Sensei" — hidup menyendiri, rutin berziarah ke makam seorang sahabat. Bagian terakhir berupa surat panjang Sensei yang membuka rahasia masa lalunya.',
    'Novel tentang rasa bersalah, kesepian, dan peralihan zaman Meiji. Karya asli Jepangnya sudah domain publik; terjemahan Inggris modern masih berhak cipta. Catatan pembaca: surat Sensei menyinggung bunuh diri — bila tema ini berat untukmu, bacalah pelan dan jangan ragu mencari teman bicara.',
    { help: true, skill: 'karisma' }),
  B('k8', 'klasik', 'Dead Poets Society', ['N. H. Kleinbaum', 1989, 'Novelisasi dari film karya Tom Schulman (1989)', 'Novel', ['store'], 'Di daftar tertulis "Death Poeth Society".'],
    'Di sekolah asrama Welton Academy yang kaku, guru bahasa Inggris John Keating mengajak murid-muridnya berdiri di atas meja dan menghidupkan puisi: "Carpe diem — raihlah hari ini." Mereka lalu menghidupkan kembali klub rahasia Dead Poets Society.',
    'Tentang keberanian menjadi diri sendiri di bawah tekanan orang tua dan tradisi. Ada peristiwa bunuh diri seorang tokoh dalam ceritanya; kisahnya jadi pengingat pentingnya didengar dan dipahami.',
    { help: true, skill: 'kreatif' }),
  B('k9', 'klasik', 'De Caelo (Tentang Langit)', ['Aristoteles', '±350 SM', 'Karya Yunani Kuno; terjemahan Inggris J. L. Stocks (1922)', 'Filsafat alam/kosmologi', ['gutenberg']],
    'Aristoteles membayangkan alam semesta berbentuk bola: bumi bulat di pusat, langit bergerak melingkar sempurna, dan benda langit tersusun dari unsur kelima, "aether", yang berbeda dari tanah, air, udara, dan api.',
    'Ia juga memberi bukti bahwa bumi bulat — bayangan melengkung bumi saat gerhana bulan dan bintang yang berubah ketika kita berjalan ke utara atau selatan. Banyak isinya kini salah menurut sains modern, tapi cara berpikirnya memengaruhi dunia selama hampir 2.000 tahun.',
    { link: G('Aristotle On the Heavens') }),
  // ------------------- MANGA -------------------
  B('m1', 'manga', 'Another', ['Yukito Ayatsuji (novel); manga oleh Hiro Kiyohara', 2009, 'Kadokawa Shoten', 'Horor misteri', ['manga', 'store']],
    'Kōichi Sakakibara pindah ke kelas 3-3 SMP Yomiyama, kelas yang menyimpan kutukan sejak 26 tahun lalu. Semua orang mengabaikan gadis berpenutup mata, Mei Misaki, seolah ia tidak ada — dan kematian aneh mulai menimpa orang-orang di sekitar kelas itu.',
    'Misteri teka-teki yang rapat: siapa "orang tambahan" di kelas itu? Seri ini diadaptasi jadi anime (2012) dan film live-action.'),
  B('m2', 'manga', 'Monster', ['Naoki Urasawa', 1994, 'Shogakukan (Big Comic Original), 18 volume', 'Thriller psikologis', ['manga']],
    'Dr. Kenzo Tenma, ahli bedah Jepang di Düsseldorf, memilih menyelamatkan nyawa seorang anak laki-laki ketimbang wali kota. Bertahun-tahun kemudian, anak itu — Johan — muncul kembali sebagai sosok yang sangat berbahaya.',
    'Tenma memburu Johan melintasi Jerman dan Ceko, menyingkap eksperimen panti asuhan era Perang Dingin. Karya besar tentang nilai nyawa manusia dan asal-usul kejahatan.'),
  B('m3', 'manga', 'Smile', ['(perlu dicek)', '—', 'Data belum terverifikasi', 'Manga', ['manga'], 'Ada beberapa karya berjudul "Smile"; kami belum bisa memastikan yang dimaksud. Tuliskan nama pengarangnya agar ringkasan bisa dilengkapi.'],
    'Rak ini masih menunggu konfirmasi judul lengkap/pengarang. Beberapa karya bernama serupa berbeda genre sama sekali, dari horor hingga memoar grafis anak (Raina Telgemeier, 2010).',
    'Sementara itu, buku ini ditandai "perlu dicek" di katalog perpustakaan rumah.'),
  B('m4', 'manga', '20th Century Boys', ['Naoki Urasawa', 1999, 'Shogakukan (Big Comic Spirits), 22 volume + 21st Century Boys', 'Misteri fiksi ilmiah', ['manga']],
    'Kenji, pemilik minimarket biasa, sadar bahwa sebuah sekte yang dipimpin sosok bertopeng bernama "Tomodachi" menjalankan rencana kiamat persis seperti "Buku Ramalan" yang ia dan teman-temannya karang waktu kecil.',
    'Cerita melompat antara masa kecil tahun 1969–70-an, 1997, dan 2014; tentang persahabatan, nostalgia, musik rock, dan tanggung jawab atas imajinasi masa kecil.'),
  B('m5', 'manga', 'Gyo', ['Junji Ito', 2001, 'Shogakukan (Big Comic Spirits), 2 volume', 'Horor', ['manga']],
    'Tadashi dan kekasihnya Kaori berlibur di Okinawa ketika ikan-ikan mulai berjalan ke darat dengan kaki mekanis aneh — disusul makhluk laut yang lebih besar — dan bau busuk menyebar ke seluruh Jepang.',
    'Horor tubuh khas Junji Ito yang absurd dan mengerikan. Cocok untuk yang kuat nyali; bukan bacaan sebelum makan.'),
  // ------------------- FIKSI MODERN -------------------
  B('f1', 'fiksi', 'Messiah', ['Boris Starling', 1999, 'HarperCollins', 'Thriller kriminal', ['store']],
    'Detektif Red Metcalfe di London memburu pembunuh berantai yang meninggalkan pola ritual dan sendok perak di mulut korbannya — petunjuk yang merujuk pada para rasul.',
    'Thriller gelap tentang obsesi dan harga yang dibayar penyidik. Diadaptasi menjadi serial BBC "Messiah" (2001).'),
  B('f2', 'fiksi', 'Pulang', ['Leila S. Chudori', 2012, 'Kepustakaan Populer Gramedia (KPG)', 'Novel sejarah', ['ipusnas', 'store']],
    'Dimas Suryo dan kawan-kawannya, wartawan yang sedang di luar negeri saat peristiwa 1965, tidak bisa pulang ke Indonesia dan akhirnya membuka restoran di Paris. Putrinya, Lintang Utara, datang ke Jakarta tahun 1998 untuk merekam sejarah keluarganya.',
    'Kisah eksil politik, identitas, dan rindu kampung halaman yang berlatar tiga peristiwa: 1965, Paris 1968, dan Reformasi 1998. Meraih Khatulistiwa Literary Award 2013.', { skill: 'karisma' }),
  B('f3', 'fiksi', 'Dunia Anna (Anna\'s World)', ['Jostein Gaarder', 2013, 'Terbit asli Anna. En fabel om klodens klima og miljø; edisi Indonesia Mizan', 'Novel filsafat/lingkungan', ['ipusnas', 'store']],
    'Anna, remaja Norwegia yang hampir berusia 16 tahun, bermimpi menjadi cicitnya sendiri, Nova, di tahun 2082 — dunia yang rusak akibat perubahan iklim dan kepunahan spesies.',
    'Gaarder (penulis Dunia Sophie) mengajak pembaca muda berpikir tentang tanggung jawab lintas generasi terhadap bumi.'),
  B('f4', 'fiksi', 'The Silent Patient', ['Alex Michaelides', 2019, 'Celadon Books', 'Thriller psikologis', ['store']],
    'Alicia Berenson, pelukis ternama, dituduh membunuh suaminya lalu berhenti bicara sama sekali. Theo Faber, psikoterapis forensik, terobsesi membuatnya bicara lagi di klinik The Grove.',
    'Dikisahkan lewat sudut pandang Theo dan buku harian Alicia, dengan twist akhir yang terkenal. Karakter pelukisnya bikin Naswa penasaran.', { skill: 'kreatif' }),
  B('f5', 'fiksi', 'Absolute Justice (Zettai Seigi)', ['Akiyoshi Rikako', 2016, 'Gentosha; edisi Indonesia Haru', 'Thriller psikologis', ['store', 'ipusnas']],
    'Lima sahabat SMA mengenal Noriko, gadis yang memegang aturan secara mutlak tanpa kompromi. Kebenaran versinya pelan-pelan jadi teror bagi hidup mereka, hingga bertahun-tahun kemudian.',
    'Novel tentang bahaya "kebenaran" yang kehilangan empati — apakah benar selalu berarti baik?'),
  B('f6', 'fiksi', 'Holy Mother', ['Akiyoshi Rikako', 2014, 'Futabasha; edisi Indonesia Haru', 'Thriller misteri', ['store', 'ipusnas']],
    'Sebuah kasus kejahatan terhadap anak mengguncang kota kecil. Seorang ibu, Honami, dilanda kecemasan demi putrinya, sementara penyidik mengejar pelaku.',
    'Dikenal dengan twist besar tentang cinta seorang ibu. Ringkasan di sini sengaja dibuat tanpa detail kekerasan.'),
  B('f7', 'fiksi', 'Assassin\'s Creed: Last Descendants — Tomb of the Khan (2) & Fate of the Gods (3)', ['Matthew J. Kirby', 2017, 'Scholastic', 'Fiksi remaja/petualangan', ['store'], 'Di daftar tertulis "Last Descendance 2 dan 3"; kami mencocokkannya dengan trilogi Last Descendants.'],
    'Buku 2 (Tomb of the Khan): para remaja keturunan Assassin dan Templar memakai Animus untuk mengulang ingatan leluhur di masa Mongol, memburu artefak Trisula Eden.',
    'Buku 3 (Fate of the Gods): perburuan berlanjut ke Norwegia era Viking, dengan pertaruhan nasib dunia dan persahabatan mereka yang retak.'),
  B('f8', 'fiksi', 'Everything Becomes F (Subete ga F ni Naru)', ['Mori Hiroshi', 1996, 'Kodansha (pemenang pertama Mephisto Prize)', 'Misteri ruang tertutup', ['store']],
    'Dosen Saikawa Sōhei dan mahasiswinya Nishinosono Moe mengunjungi laboratorium terpencil di sebuah pulau, tempat jenius Magata Shiki hidup terisolasi selama 15 tahun — lalu terjadi kejahatan di ruang yang mustahil dimasuki.',
    'Misteri logika bernuansa pemrograman komputer; judulnya teka-teki heksadesimal. Handoyo jelas suka.', { skill: 'logika' }),
  B('f9', 'fiksi', 'Life for Sale (Inochi Urimasu)', ['Yukio Mishima', 1968, 'Terbit berseri di Weekly Playboy (Jepang); terjemahan Inggris 2019', 'Novel satir', ['store']],
    'Setelah hidupnya terasa hampa, Hanio memasang iklan di koran: "Hidup dijual." Para pembeli datang dengan permintaan aneh, dan setiap misi justru menyeretnya ke petualangan absurd — mata-mata, vampir, dan sindikat.',
    'Satir gelap tentang makna hidup di masyarakat modern. Karena premisnya soal keinginan mati, bacalah dengan kesadaran bahwa novel ini justru berakhir dengan Hanio yang ingin hidup.', { help: true }),
  B('f10', 'fiksi', 'Normal People', ['Sally Rooney', 2018, 'Faber & Faber', 'Novel romansa kontemporer', ['store']],
    'Connell dan Marianne tumbuh di kota kecil Irlandia: Connell populer tapi miskin, Marianne kaya tapi terasing. Hubungan mereka putus-sambung dari SMA hingga Trinity College Dublin.',
    'Tentang kelas sosial, komunikasi yang gagal, dan kesehatan mental. Diadaptasi jadi serial BBC/Hulu (2020).', { skill: 'karisma' }),
  // ------------------- NON-FIKSI -------------------
  B('n1', 'nonfiksi', 'Sobotta: Atlas Anatomi Manusia', ['Johannes Sobotta (kini disunting F. Paulsen & J. Waschke)', 1904, 'Elsevier; edisi Indonesia EGC', 'Atlas kedokteran', ['store', 'perpus'], 'Di daftar tertulis "Sobatta".'],
    'Atlas anatomi klasik untuk mahasiswa kedokteran sejak awal abad ke-20. Ilustrasinya sangat detail: tulang, otot, pembuluh darah, saraf, dan organ, per region tubuh.',
    'Edisi modern dibagi beberapa jilid (anatomi umum & muskuloskeletal; organ dalam; kepala, leher, dan neuroanatomi) serta dilengkapi tabel otot.', { skill: 'logika' }),
  B('n2', 'nonfiksi', 'Human Physiology: From Cells to Systems (Fisiologi Manusia)', ['Lauralee Sherwood', 1989, 'Cengage Learning; edisi Indonesia EGC', 'Buku ajar fisiologi', ['store', 'perpus'], 'Di daftar tertulis "Sherwood".'],
    'Buku ajar fisiologi yang terkenal mudah dipahami: dari sel, saraf, otot, jantung, pernapasan, ginjal, pencernaan, hingga hormon dan reproduksi.',
    'Benang merahnya adalah homeostasis — bagaimana semua sistem tubuh bekerja sama menjaga lingkungan internal tetap stabil.'),
  B('n3', 'nonfiksi', 'The Evolution of Cooperation', ['Robert Axelrod', 1984, 'Basic Books', 'Teori permainan/sains sosial', ['store']],
    'Axelrod mengadakan turnamen komputer Prisoner\'s Dilemma berulang. Pemenangnya ternyata strategi sederhana "Tit for Tat" kiriman Anatol Rapoport: mulai dengan bekerja sama, lalu balas apa pun yang dilakukan lawan.',
    'Pelajarannya: jadilah baik, cepat membalas, mudah memaafkan, dan jelas. Kerja sama bisa tumbuh bahkan di antara pihak yang egois — asal mereka akan bertemu lagi di masa depan. Cocok untuk urusan tetangga!'),
  B('n4', 'nonfiksi', 'The Extended Phenotype', ['Richard Dawkins', 1982, 'Oxford University Press', 'Biologi evolusi', ['store']],
    'Lanjutan gagasan The Selfish Gene: efek gen tidak berhenti di tubuh organisme. Bendungan berang-berang, sarang burung, bahkan perilaku inang yang dimanipulasi parasit adalah "fenotipe yang diperluas".',
    'Dawkins sendiri menyebut buku ini karyanya yang paling penting secara ilmiah. Lebih teknis dari The Selfish Gene.'),
  B('n5', 'nonfiksi', 'Perempuan di Titik Nol', ['Nawal El Saadawi', 1975, 'Terbit asli Imra\'a \'inda nuqtat al-sifr; edisi Indonesia Yayasan Pustaka Obor', 'Novel berbasis kisah nyata', ['ipusnas', 'store']],
    'Seorang psikiater mewawancarai Firdaus, perempuan di penjara Qanatir, Mesir, yang menunggu hukuman mati. Firdaus menceritakan hidupnya sejak kecil: kemiskinan, pernikahan paksa, dan eksploitasi oleh laki-laki di sekitarnya.',
    'Suara protes yang kuat terhadap penindasan perempuan. Ringkasan ini tidak memuat detail kekerasan; buku aslinya cukup berat secara emosional.', { skill: 'karisma' }),
  // ------------------- UPGRADE -------------------
  B('u1', 'upgrade', 'Blink', ['Malcolm Gladwell', 2005, 'Little, Brown and Company', 'Psikologi populer', ['store']],
    'Tentang "thin-slicing": kemampuan otak mengambil keputusan dalam dua detik pertama. Contohnya patung Yunani kuno yang terasa "palsu" oleh para ahli sebelum mereka bisa menjelaskan alasannya.',
    'Tapi intuisi juga bisa bias — Gladwell membahas prasangka tersembunyi dan keputusan tergesa. Pesannya: latih intuisi, kenali kapan ia menipu.'),
  B('u2', 'upgrade', 'How to Win Friends and Influence People', ['Dale Carnegie', 1936, 'Simon & Schuster; edisi Indonesia Gramedia', 'Pengembangan diri', ['store', 'ipusnas'], 'Di daftar tertulis "How to Influence People".'],
    'Prinsip-prinsip klasik: jangan mengkritik, mengutuk, atau mengeluh; tunjukkan minat yang tulus; ingat nama orang; jadilah pendengar yang baik; bicarakan hal yang diminati lawan bicara.',
    'Sudah hampir 90 tahun, tapi masih relevan untuk kerja, bertetangga, sampai menawar harga lukisan di toko online.', { skill: 'karisma' }),
  B('u3', 'upgrade', 'Berani Tidak Disukai', ['Ichiro Kishimi & Fumitake Koga', 2013, 'Diamond, Inc.; edisi Indonesia Gramedia Pustaka Utama', 'Psikologi/filsafat', ['ipusnas', 'store']],
    'Dialog lima malam antara seorang filsuf dan pemuda yang skeptis, membedah psikologi Alfred Adler: trauma tidak menentukan hidup kita, semua masalah adalah masalah hubungan antarmanusia.',
    'Konsep kunci: memisahkan tugas (urusanku vs urusanmu), berhenti mencari pengakuan, dan menemukan kebahagiaan lewat kontribusi.', { skill: 'karisma' }),
  B('u4', 'upgrade', 'Seni Tinggal di Bumi', ['Farah Qoonita', 2020, 'Qoonita Publishing', 'Pengembangan diri Islami', ['store'], 'Tahun/penerbit mohon dicek ulang di katalog resmi penulis.'],
    'Kumpulan renungan tentang cara menjalani hidup dengan tenang: menerima ujian, mengelola ekspektasi, merawat hati, dan memaknai hidup sebagai perjalanan pulang.',
    'Ditulis dengan bahasa hangat yang akrab untuk pembaca muda, dengan landasan nilai-nilai Islam.', { skill: 'karisma' }),
  // ------------------- iPUSNAS & PERPUS -------------------
  B('i1', 'ipusnas', 'Catatan dari Bawah Tanah (Notes from Underground)', ['Fyodor Dostoevsky', 1864, 'Terbit di majalah Epokha; terjemahan Inggris Constance Garnett (1918)', 'Novela filosofis', ['ipusnas', 'gutenberg']],
    'Bagian pertama berupa monolog "manusia bawah tanah", pegawai pensiunan di St. Petersburg yang pahit dan menolak gagasan bahwa manusia selalu bertindak rasional demi keuntungannya.',
    'Bagian kedua mengenang peristiwa memalukan dari masa mudanya. Sering disebut salah satu karya eksistensialis pertama.', { link: G('Notes from the Underground Dostoyevsky') }),
  B('i2', 'ipusnas', 'Antologi Sastra Daerah Nusantara', ['Berbagai penyusun', '—', 'Beberapa edisi (mis. Yayasan Obor Indonesia)', 'Antologi', ['ipusnas', 'perpus'], 'Ada beberapa buku antologi dengan judul serupa; data edisi mohon dicek di iPusnas.'],
    'Kumpulan cerita, puisi, dan legenda dari berbagai daerah di Indonesia yang diterjemahkan ke bahasa Indonesia — dari Aceh hingga Papua.',
    'Cocok untuk mengenal kekayaan sastra lisan dan tulisan Nusantara di luar karya berbahasa Indonesia.'),
  B('i3', 'ipusnas', 'Rintihan Burung Kedasih', ['Pandir Kelana (Slamet Danusudirdjo)', 1984, 'Sinar Harapan (1984); Gramedia Pustaka Utama (1992)', 'Roman revolusi', ['ipusnas', 'perpus']],
    'Roman revolusi yang berlatar 1948–1949, fase akhir perang mempertahankan kemerdekaan, di Karesidenan Pati, Jawa Tengah — wilayah tempat konsolidasi pemerintah sipil dan tentara berjalan sangat sulit.',
    'Pandir Kelana, penulis sekaligus tentara, menulis delapan novel revolusi yang tokohnya saling terkait; salah satunya "Kereta Api Terakhir" yang difilmkan.'),
  B('i4', 'ipusnas', 'Sorga bagi si Buta', ['(perlu dicek)', '—', 'Data belum terverifikasi', '—', ['ipusnas', 'perpus'], 'Kami belum menemukan data bibliografi yang pasti untuk judul ini. Silakan cek langsung di iPusnas/OPAC perpustakaan.'],
    'Buku ini ada di daftar pemilik rumah, tetapi metadata aslinya belum bisa kami verifikasi, jadi ringkasan belum ditulis agar tidak mengarang isi.',
    'Kalau kamu menemukan pengarang atau penerbitnya, katalog perpustakaan rumah bisa dilengkapi.'),
  B('i5', 'ipusnas', 'Dunia Maya (Maya)', ['Jostein Gaarder', 1999, 'Terbit asli Maya; edisi Indonesia Mizan', 'Novel filsafat', ['ipusnas']],
    'Di sebuah resor di Fiji, ilmuwan evolusi Frank Andersen bertemu pasangan Spanyol misterius, Ana dan José, yang tampak hidup di antara kenyataan dan lukisan Goya "La Maja".',
    'Novel tentang evolusi, kesadaran, dan pertanyaan besar: apa arti keberadaan manusia di alam semesta? Catatan: judul "Dunia Anna" juga ada di rak Buku Lain.'),
  B('i6', 'ipusnas', 'Robohnya Surau Kami', ['A. A. Navis', 1956, 'Kumpulan cerpen; cerpen utama terbit 1955 di majalah Kisah; kini Gramedia Pustaka Utama', 'Cerpen', ['ipusnas', 'store']],
    'Kakek garin penjaga surau yang taat beribadah terguncang setelah mendengar cerita Ajo Sidi tentang Haji Saleh — orang yang rajin sembahyang tetapi tetap dimasukkan ke neraka karena menelantarkan kampung dan keluarganya.',
    'Satire tajam tentang ibadah yang melupakan tanggung jawab sosial. Salah satu cerpen paling terkenal dalam sastra Indonesia.', { skill: 'karisma' }),
  B('i7', 'ipusnas', 'Larasati', ['Pramoedya Ananta Toer', 2000, 'Lentera Dipantara (versi buku)', 'Roman revolusi', ['ipusnas', 'store']],
    'Ara (Larasati), bintang film yang populer, bergerak dari daerah pendudukan Belanda ke Yogyakarta di masa revolusi. Ia menyaksikan pengkhianatan, oportunisme, dan kerasnya perjuangan dari sudut pandang perempuan.',
    'Menyoroti bagaimana perempuan memilih keberpihakan di tengah perang, dengan gaya khas Pram yang lugas.'),
  B('i8', 'ipusnas', 'The Blue Manuscript', ['Sabiha Al Khemir', 2008, 'Verso Books', 'Novel sejarah/misteri', ['ipusnas', 'store']],
    'Tim arkeolog internasional menggali situs di desa terpencil Mesir untuk mencari Manuskrip Biru — Al-Qur\'an legendaris yang ditulis di atas perkamen biru.',
    'Kisahnya diselingi kesaksian kaligrafer abad pertengahan pembuat manuskrip itu. Tentang seni kaligrafi Islam, perbedaan budaya Timur–Barat, dan apa arti "berhasil".', { skill: 'kreatif' }),
  B('i9', 'ipusnas', 'The Selfish Gene', ['Richard Dawkins', 1976, 'Oxford University Press', 'Biologi evolusi populer', ['ipusnas', 'store']],
    'Dawkins memandang evolusi dari sudut pandang gen: makhluk hidup adalah "mesin kelangsungan hidup" yang dibangun gen untuk mereplikasi diri.',
    'Anehnya, gen yang "egois" bisa menghasilkan perilaku altruistik. Buku ini juga memperkenalkan istilah "meme". Pasangannya di rak Non-fiksi: The Extended Phenotype.'),
  B('i10', 'ipusnas', 'Rumah Lebah', ['Ruwi Meita', 2008, 'GagasMedia', 'Thriller psikologis', ['ipusnas', 'store'], 'Tahun/penerbit mohon dicek ulang di iPusnas.'],
    'Keluarga Winaya pindah ke rumah di tepi hutan. Putri mereka, Mala, anak jenius yang punya "teman-teman" yang hanya dia yang bisa lihat, dan keanehan demi keanehan mulai terjadi.',
    'Thriller psikologis Indonesia tentang rahasia keluarga dan kondisi kejiwaan, dengan suasana mencekam.'),
];

const ACCESS_TEXT = (b) => b.access.map((a) => `• ${ACCESS[a].label}: ${ACCESS[a].note}`).join('\n');
for (const b of LIST) {
  b.pages[0] = `${b.title}\nPengarang: ${b.author}\nTerbit pertama: ${b.year}\nPenerbit/edisi: ${b.publisher}\nGenre: ${b.genre}${b.verify ? `\n\n⚠️ Catatan katalog: ${b.verify}` : ''}\n\nCara membaca versi lengkap secara legal:\n${ACCESS_TEXT(b)}${b.link ? `\n• Tautan: ${b.link}` : ''}`;
  b.pages.push('Halaman ini berisi ringkasan & ulasan buatan perpustakaan rumah, bukan isi buku aslinya. Hargai penulis dengan membaca versi resminya — gratis lewat iPusnas bila tersedia.');
  BOOKS.push(b);
}
export const ACCESS_INFO = [
  'Aplikasi iPusnas (gratis): semua buku di rak "Ada di iPusnas & Perpus" dapat dipinjam online. Beberapa judul lain — Catatan Seorang Demonstran, Robohnya Surau Kami, Berani Tidak Disukai, dan Pulang — umumnya juga tersedia di sana.',
  'Domain publik (gratis): Crime and Punishment, Botchan, De Caelo, Notes from Underground, Max Havelaar, dan The Prince sudah bebas hak cipta dan bisa diunduh legal di Project Gutenberg (umumnya terjemahan Inggris).',
  'Toko e-book resmi (berbayar): mayoritas fiksi modern, buku Upgrade, serta buku ajar seperti Sobotta dan Sherwood tersedia di Google Play Books, Amazon Kindle, atau Gramedia Digital.',
  'Manga: Monster, 20th Century Boys, Gyo, dan Another bisa dibaca lewat platform/penerbit berlisensi.',
];
