// ============================================================
//  PERLUASAN HALAMAN BUKU
//  - Karya domain publik: panduan bab demi bab + kutipan terjemahan sendiri.
//  - Karya modern berhak cipta: halaman kajian (tokoh, tema, diskusi, rekomendasi,
//    catatan Naswa) — ditulis sendiri, BUKAN salinan isi buku.
// ============================================================
import { BOOKS } from './books.js';

const PD = {
  k1: [
    'BAGIAN I — Raskolnikov, mantan mahasiswa hukum yang hidup miskin di kamar sempit, bergulat dengan sebuah "teori" dan rencana. Di kedai minum ia bertemu Marmeladov, pegawai pemabuk yang bercerita tentang putrinya, Sonya, yang berkorban demi keluarga. Surat dari ibunya mengabarkan adiknya, Dunya, akan menikah dengan Luzhin demi keamanan finansial — sesuatu yang membuat Raskolnikov marah. Bagian ini berakhir dengan kejahatan berat yang ia lakukan, dikisahkan Dostoevsky secara singkat namun menegangkan.',
    'BAGIAN II — Demam, ketakutan, dan pingsan di kantor polisi. Sahabatnya, Razumikhin, merawatnya. Raskolnikov menyaksikan Marmeladov tertabrak kereta kuda dan memberikan seluruh uangnya untuk keluarga itu — tanda bahwa di balik "teori"-nya masih ada belas kasih.',
    'BAGIAN III — Ibu dan Dunya tiba di Petersburg. Raskolnikov menolak Luzhin. Ia bertemu penyidik Porfiry Petrovich yang telah membaca artikelnya tentang orang "biasa" dan "luar biasa". Percakapan mereka seperti permainan catur psikologis.',
    'BAGIAN IV — Svidrigailov, mantan majikan Dunya yang misterius, muncul. Luzhin diusir keluarga. Raskolnikov mendatangi Sonya dan memintanya membacakan kisah kebangkitan Lazarus — salah satu adegan paling terkenal dalam sastra dunia.',
    'BAGIAN V — Luzhin mencoba memfitnah Sonya mencuri, tetapi kebohongannya terbongkar. Katerina Ivanovna, ibu tiri Sonya, jatuh sakit parah. Raskolnikov mengakui perbuatannya kepada Sonya, yang memintanya menebus dosa secara terbuka.',
    'BAGIAN VI — Porfiry menyatakan tahu kebenarannya dan menyarankan Raskolnikov menyerahkan diri demi keringanan dan demi jiwanya sendiri. Dunya berhasil lepas dari Svidrigailov. Setelah berpamitan kepada ibu dan adiknya, Raskolnikov akhirnya mengaku di kantor polisi.',
    'EPILOG — Di Siberia, Sonya setia mengikutinya. Awalnya Raskolnikov tetap dingin, sampai suatu pagi ia menyadari cintanya dan mulai melihat kemungkinan hidup baru. Dostoevsky menutup novel dengan harapan: kisah seorang manusia yang perlahan diperbarui.',
    'KUTIPAN (terjemahan bebas dari naskah domain publik): "Penderitaan dan rasa sakit selalu menyertai pikiran yang luas dan hati yang dalam." · "Orang yang sungguh besar, menurutku, pasti merasakan kesedihan besar di dunia ini."',
    'TOKOH: Rodion Raskolnikov (tokoh utama) · Sonya Marmeladova (hati nurani novel) · Porfiry Petrovich (penyidik) · Dunya (adik) · Razumikhin (sahabat setia) · Svidrigailov (sosok gelap) · Luzhin (tunangan Dunya yang angkuh).',
    'PERTANYAAN KLUB BUKU: (1) Apakah "teori" Raskolnikov runtuh karena logika atau karena nurani? (2) Mengapa Porfiry tidak langsung menangkapnya? (3) Apa peran Sonya bagi pertobatan Raskolnikov? — Catatan Naswa: "Novel ini bukan soal siapa pelakunya, tapi tentang bagaimana manusia tidak bisa lari dari dirinya sendiri."',
  ],
  k2: [
    'BAB 1–2 — Botchan, anak Tokyo yang sejak kecil nekat dan jujur, hanya disayangi pengasuh tua bernama Kiyo. Setelah lulus sekolah fisika, ia menerima tawaran mengajar matematika di sebuah sekolah menengah di Shikoku (latar yang terinspirasi Matsuyama).',
    'BAB 3–4 — Murid-murid mengolok-oloknya: mencatat berapa mangkuk mi tempura yang ia makan, lalu mengisi ranjangnya dengan belalang saat ia bertugas jaga asrama. Botchan menuntut pertanggungjawaban, tapi sekolah lebih sibuk menjaga muka.',
    'BAB 5–7 — Ia berkenalan dengan para guru yang dijuluki sesuai penampilan: Landak (Yamaarashi), guru matematika yang blak-blakan; Kemeja Merah, wakil kepala yang licik; Si Badut, pengikut setia Kemeja Merah; dan Labu (Uranari), guru lembut yang tunangannya, "Madonna", direbut Kemeja Merah.',
    'BAB 8–10 — Intrik kantor makin kotor: Labu dipindahkan jauh, Landak dijebak dalam keributan antarpelajar dan dipaksa mundur. Botchan akhirnya sadar siapa yang benar-benar jujur.',
    'BAB 11 — Botchan dan Landak mengintai Kemeja Merah dan Si Badut, lalu "menghukum" mereka dengan cara yang lucu. Botchan pulang ke Tokyo, bekerja sebagai teknisi trem, dan tinggal bersama Kiyo sampai akhir hayatnya.',
    'KUTIPAN (terjemahan bebas dari naskah domain publik): "Sejak kecil, sifat nekat warisan ayahku hanya membuatku rugi." — kalimat pembuka yang langsung memperkenalkan watak tokohnya.',
    'TEMA & CATATAN NASWA: kejujuran vs kemunafikan, orang kota vs orang daerah, dan kasih sayang tulus (Kiyo). "Botchan itu ceroboh, tapi hatinya lurus. Kadang dunia butuh orang yang terlalu jujur."',
  ],
  k7: [
    'BAGIAN 1 — "Sensei dan Aku". Seorang mahasiswa berkenalan dengan pria yang ia panggil Sensei di pantai Kamakura. Sensei hidup tenang bersama istrinya, jarang bergaul, dan rutin berziarah ke makam seorang sahabat. Ia berkata bahwa manusia bisa berubah jahat ketika dihadapkan pada uang dan cinta.',
    'BAGIAN 2 — "Orang Tua dan Aku". Sang mahasiswa pulang kampung karena ayahnya sakit parah. Kaisar Meiji wafat — tanda berakhirnya sebuah zaman. Sebuah surat tebal dari Sensei tiba, dan si mahasiswa bergegas naik kereta ke Tokyo.',
    'BAGIAN 3 — "Wasiat Sensei". Surat panjang Sensei mengisahkan masa mudanya: ditipu pamannya soal warisan, lalu tinggal di rumah seorang janda bersama sahabatnya, K. Keduanya jatuh cinta pada putri si janda. Sensei bertindak diam-diam dan menikahinya, sementara K kemudian meninggal karena bunuh diri. Rasa bersalah itu menghantui Sensei seumur hidup.',
    'TEMA: kesepian manusia modern, rasa bersalah yang dipendam, egoisme, dan perpindahan dari zaman Meiji ke era baru. Judul "Kokoro" berarti hati, pikiran, dan perasaan sekaligus.',
    'CATATAN PEMBACA: novel ini menyinggung bunuh diri sebagai bagian dari kisah, tanpa menjadikannya jalan keluar. Jika kamu sedang merasa berat, ceritakan ke orang terdekat atau hubungi layanan SEJIWA 119 ext 8. Catatan Naswa: "Rahasia yang dipendam terlalu lama bisa melukai. Aku bersyukur Handoyo selalu mau mendengar."',
  ],
  i1: [
    'BAGIAN 1 — "Bawah Tanah". Narator tanpa nama, pensiunan pegawai berusia empat puluhan, berbicara langsung kepada pembaca. Ia menyebut dirinya orang sakit dan pendendam, lalu mengejek keyakinan bahwa manusia selalu memilih yang paling menguntungkan dirinya.',
    'Menurutnya, manusia kadang sengaja memilih yang merugikan hanya untuk membuktikan bahwa ia bebas dan "bukan tuts piano". Ia menolak gagasan "istana kristal": masyarakat rasional sempurna yang meramalkan semua tindakan manusia.',
    'BAGIAN 2 — "Tentang Salju Basah". Ia mengenang masa mudanya: berusaha "membalas" seorang perwira yang tak menyadari kehadirannya, lalu memaksa ikut jamuan perpisahan teman sekolah yang meremehkannya — dan mempermalukan diri sendiri.',
    'Malam itu ia bertemu Liza, perempuan muda yang hidupnya sulit. Ia berkhotbah panjang tentang masa depan Liza, tetapi ketika Liza datang dengan tulus, ia justru menyakitinya karena malu dan takut dicintai.',
    'KUTIPAN (terjemahan bebas dari naskah domain publik): "Aku orang sakit… Aku orang yang pendendam." — kalimat pembuka yang terkenal.',
    'TEMA & CATATAN NASWA: kesadaran berlebihan yang melumpuhkan, harga diri yang rapuh, dan kebebasan kehendak. "Tokohnya menyebalkan, tapi jujur sekali tentang sisi gelap manusia. Buku ini bikin aku ingin lebih berani menerima kebaikan orang."',
  ],
  k4a: [
    'STRUKTUR — Novel dibuka oleh Batavus Droogstoppel, makelar kopi Amsterdam yang kikir dan membosankan. Ia menerima bungkusan naskah dari kenalan lama bernama "Sjaalman". Naskah itu kemudian diolah Stern, pemuda Jerman yang lebih berperasaan, menjadi kisah Max Havelaar.',
    'HAVELAAR DI LEBAK — Havelaar ditugaskan sebagai asisten residen di Lebak, Banten. Ia mendapati rakyat diperas: kerbau dirampas, kerja paksa, dan penderitaan akibat sistem tanam paksa, dengan keterlibatan bupati setempat.',
    'Havelaar melaporkan penyalahgunaan itu kepada atasannya. Alih-alih didukung, ia ditegur dan dipindahkan. Ia memilih mengundurkan diri daripada berkhianat pada nuraninya.',
    'SAIDJAH DAN ADINDA — Kisah sisipan yang paling dikenang: Saidjah, pemuda desa yang kerbaunya dirampas, merantau untuk mengumpulkan uang demi menikahi Adinda. Ketika ia pulang, desa dan keluarga Adinda telah hancur oleh kekerasan kolonial. Kisah ini membuat pembaca Eropa tersentuh.',
    'PENUTUP — Di akhir, pengarang (Multatuli, "aku yang banyak menderita") mengambil alih narasi dan langsung menggugat Raja Belanda. Buku ini ikut mendorong perdebatan yang kemudian melahirkan Politik Etis (1901).',
    'CATATAN — Pramoedya Ananta Toer menyebut Max Havelaar sebagai "buku yang membunuh kolonialisme". Catatan Naswa: "Satu buku bisa mengguncang sebuah kerajaan. Kata-kata itu kuat."',
  ],
  k4b: [
    'BAB 1–11 — Jenis-jenis negara: warisan, baru, campuran, dan negara gereja. Machiavelli membahas cara mempertahankan wilayah baru, pentingnya hadir langsung, dan contoh Cesare Borgia sebagai pemimpin yang cerdik.',
    'BAB 12–14 — Kekuatan militer. Tentara bayaran dianggap tidak setia dan berbahaya; negara harus punya pasukan sendiri. Pemimpin wajib mempelajari seni perang di masa damai.',
    'BAB 15–19 — Watak penguasa. Bab 17 terkenal dengan pertanyaan: lebih baik dicintai atau ditakuti? Jawaban Machiavelli: idealnya keduanya, tetapi jika harus memilih, lebih aman ditakuti — asalkan tidak dibenci. Bab 18 memakai perumpamaan rubah (cerdik mengenali jebakan) dan singa (kuat menakuti serigala).',
    'BAB 20–23 — Benteng, reputasi, penasihat, dan bahaya penjilat. Pemimpin bijak memilih penasihat cerdas dan hanya meminta nasihat ketika ia membutuhkannya.',
    'BAB 24–26 — Nasib (fortuna) dan kecakapan (virtù). Nasib menguasai separuh tindakan kita, separuh lagi ada di tangan kita. Buku ditutup dengan seruan agar Italia dipersatukan dan dibebaskan dari kekuasaan asing.',
    'KUTIPAN (terjemahan bebas dari naskah domain publik): "Lebih aman ditakuti daripada dicintai, bila salah satunya harus dilepas." · Catatan Naswa: "Buku yang dingin tapi jujur tentang kekuasaan. Handoyo bilang ini mirip rapat divisi di kantornya, haha."',
  ],
  k9: [
    'BUKU I — Alam semesta sempurna, terbatas, dan bulat. Aristoteles membedakan gerak lurus (unsur di bumi) dan gerak melingkar (benda langit). Langit dianggap tidak dilahirkan dan tidak musnah.',
    'BUKU II — Bintang dan planet melekat pada bola-bola langit yang berputar. Bumi berada diam di pusat. Bukti kebulatan bumi: bayangan melengkung saat gerhana bulan dan perubahan rasi bintang ketika bepergian ke utara atau selatan.',
    'BUKU III–IV — Tentang unsur tanah, air, udara, dan api; berat dan ringan; serta kecenderungan setiap unsur menuju "tempat alaminya".',
    'WARISAN — Model geosentris Aristoteles, disempurnakan Ptolemaios, bertahan hingga Revolusi Kopernikus. Sains modern membuktikan banyak klaimnya keliru, tetapi semangatnya — mencari penjelasan rasional berdasarkan pengamatan — tetap menjadi fondasi ilmu pengetahuan.',
    'Catatan Naswa: "Malam ini aku dan Handoyo pakai teleskop di taman. Bayangkan, dua ribu tahun lalu orang sudah menebak bumi bulat hanya dari bayangan gerhana!"',
  ],
  b10: [
    'BAGIAN 1 — Watson, dokter militer yang pulang dari Afganistan, mencari tempat tinggal murah dan dikenalkan pada Sherlock Holmes. Mereka menyewa kamar bersama di Baker Street 221B.',
    'Watson menyusun daftar "batas pengetahuan" Holmes: sangat mendalam soal kimia dan sensasional kriminal, tetapi tidak tahu bahwa bumi mengelilingi matahari — karena menurut Holmes, otak adalah loteng kecil yang hanya boleh diisi hal berguna.',
    'Inspektur Gregson dan Lestrade meminta bantuan atas sebuah kematian di rumah kosong Lauriston Gardens. Di dinding tertulis kata RACHE ("dendam" dalam bahasa Jerman). Holmes menganalisis jejak sepatu, abu cerutu, dan jejak kereta, lalu menjebak pelaku lewat iklan cincin yang hilang.',
    'BAGIAN 2 — Kisah melompat ke Utah beberapa dekade sebelumnya: John Ferrier dan putri angkatnya, Lucy, serta Jefferson Hope yang mencintai Lucy. Tekanan komunitas dan kekuasaan merenggut kebahagiaan mereka, memicu dendam panjang yang berujung di London.',
    'PENUTUP — Holmes menjelaskan "penalaran mundur": dari akibat menelusuri penyebab. Ia kesal karena polisi mendapat pujian di koran; Watson berjanji akan menuliskan kisah sebenarnya.',
    'KUTIPAN (terjemahan bebas dari naskah domain publik): "Adalah kesalahan besar berteori sebelum memiliki data." · Catatan Naswa: "Holmes itu bapaknya olah TKP modern. Sayang dia belum kenal DNA!"',
  ],
  b11: [
    'PEMBUKA — Narator menjelaskan kemampuan analitis: pemain catur hanya menghitung, sedangkan pemain whist yang baik mengamati lawan. Dupin mampu "membaca pikiran" sang narator hanya dari mengamati arah pandang dan gerak-geriknya.',
    'KASUS — Koran memberitakan kematian dua perempuan di sebuah apartemen lantai empat di Rue Morgue. Pintu terkunci dari dalam, uang tidak diambil, dan para saksi mendengar dua suara — satu berbahasa Prancis, satu lagi dalam "bahasa asing" yang tiap saksi tebak berbeda-beda.',
    'PENALARAN DUPIN — Polisi fokus pada hal rumit; Dupin mencari yang janggal. Paku jendela yang tampak utuh ternyata patah. Penangkal petir dekat jendela bisa dipanjat oleh makhluk yang sangat lincah. Suara yang tak dikenali siapa pun berarti bukan suara manusia.',
    'PENYELESAIAN — Dupin memasang iklan untuk pemilik hewan yang hilang. Seorang pelaut datang dan mengaku orangutan peliharaannya kabur. Tidak ada pembunuh manusia; kebenaran tersembunyi di tempat yang tidak terpikirkan.',
    'CATATAN — Poe melahirkan pola cerita detektif: detektif jenius, sahabat pencerita, polisi yang kalah cerdik, dan misteri ruang terkunci. Catatan Naswa: "Pelajaran forensik: jangan abaikan bukti yang tidak cocok dengan teorimu."',
  ],
};

// ------- karya modern: kajian (tidak menyalin isi) -------
const STUDY = {
  k3: { tokoh: 'Santiago (gembala muda) · Melkisedek (Raja Salem) · Pedagang kristal di Tanger · Orang Inggris yang mencari alkimia · Fatima (gadis oase) · Sang Alkemis', tema: ['Legenda Pribadi: panggilan hidup setiap orang', 'Membaca pertanda dalam hidup sehari-hari', 'Harta sering ditemukan di tempat kita berangkat', 'Cinta sejati tidak menghalangi impian'], tanya: ['Apa "Legenda Pribadi"-mu?', 'Mengapa pedagang kristal takut mewujudkan mimpinya?'], mirip: 'Siddhartha (Hermann Hesse), Sang Pemimpi (Andrea Hirata)', naswa: 'Setiap kali ragu menjual lukisan, aku ingat Santiago: mimpi harus dijalani, bukan disimpan di etalase.' },
  k5: { tokoh: 'Sukartono (Tono), dokter yang sibuk · Sumartini (Tini), istri yang modern dan mandiri · Rohayah (Yah), sahabat masa kecil Tono', tema: ['Pernikahan tanpa komunikasi', 'Benturan tradisi dan modernitas tahun 1930-an', 'Kesepian di tengah kesibukan'], tanya: ['Siapa sebenarnya yang "terbelenggu" dalam novel ini?', 'Apa yang bisa dilakukan Tono dan Tini agar saling memahami?'], mirip: 'Layar Terkembang (Sutan Takdir Alisjahbana)', naswa: 'Novel ini bikin aku dan Handoyo janji: sesibuk apa pun, malam hari tetap ngobrol sebelum tidur.' },
  k6: { tokoh: 'Soe Hok Gie · kawan-kawan mahasiswa UI · para pendaki Mapala UI', tema: ['Idealisme dan keberanian berpikir bebas', 'Kritik terhadap kekuasaan', 'Cinta pada alam dan gunung', 'Kesepian orang yang berprinsip'], tanya: ['Bagaimana menjaga idealisme saat dewasa?', 'Apa arti "lebih baik diasingkan daripada menyerah pada kemunafikan" bagimu?'], mirip: 'Pergolakan Pemikiran Islam (Ahmad Wahib)', naswa: 'Gie menulis dengan jujur sekali. Aku jadi ingin rajin menulis jurnal lagi di samping kanvas.' },
  k8: { tokoh: 'John Keating (guru bahasa Inggris) · Todd Anderson (murid pemalu) · Neil Perry (bermimpi jadi aktor) · Knox Overstreet · Charlie Dalton', tema: ['Carpe diem — raih hari ini', 'Tekanan orang tua dan sekolah', 'Puisi sebagai cara menjadi manusia seutuhnya', 'Keberanian menjadi diri sendiri'], tanya: ['Apakah metode Keating sepenuhnya benar?', 'Apa yang seharusnya dilakukan orang dewasa di sekitar Neil?'], mirip: 'Film Dead Poets Society (1989)', naswa: 'Tragedi di buku ini mengingatkan: dengarkan anak muda sebelum terlambat. Kalau ada yang merasa terpojok, ajak bicara & cari bantuan (SEJIWA 119 ext 8).', help: true },
  m1: { tokoh: 'Kōichi Sakakibara (murid pindahan) · Mei Misaki (gadis berpenutup mata) · kelas 3-3', tema: ['Kutukan dan ketakutan kolektif', 'Pengucilan sebagai "aturan"', 'Ingatan yang dimanipulasi'], tanya: ['Mengapa satu kelas rela mengabaikan seseorang?', 'Apa rasanya menjadi "yang tidak ada"?'], mirip: 'Novel Another (Yukito Ayatsuji), anime Another (2012)', naswa: 'Horornya pelan tapi nempel. Jangan baca sendirian malam-malam di perpustakaan lantai 2!' },
  m2: { tokoh: 'Dr. Kenzo Tenma · Johan Liebert · Nina Fortner (Anna) · Inspektur Heinrich Lunge', tema: ['Apakah semua nyawa sama berharganya?', 'Identitas dan masa lalu yang dihapus', 'Kejahatan: bawaan atau bentukan?'], tanya: ['Apakah keputusan Tenma di awal cerita benar?', 'Siapa "monster" sebenarnya?'], mirip: 'Pluto & 20th Century Boys (Naoki Urasawa)', naswa: 'Inspektur Lunge dengan kebiasaan "mengetik" ingatan di jarinya itu ikon penyidik fiksi favoritku.' },
  m4: { tokoh: 'Kenji Endo (pemilik minimarket) · Otcho · Yukiji · Kanna (keponakan Kenji) · "Tomodachi" (sosok bertopeng)', tema: ['Persahabatan masa kecil', 'Nostalgia & tanggung jawab atas imajinasi', 'Rock and roll melawan ketakutan'], tanya: ['Mengapa "Buku Ramalan" masa kecil bisa jadi kenyataan?', 'Siapa yang pantas disebut pahlawan?'], mirip: 'Monster (Naoki Urasawa)', naswa: 'Bikin kangen main di markas rahasia bareng teman SD.' },
  m5: { tokoh: 'Tadashi · Kaori (kekasihnya)', tema: ['Horor tubuh (body horror)', 'Teknologi yang lepas kendali', 'Ketakutan pada bau dan pembusukan'], tanya: ['Mengapa horor Junji Ito terasa begitu mengganggu?'], mirip: 'Uzumaki & Tomie (Junji Ito)', naswa: 'Setelah baca ini, aku nggak mau makan ikan asin seminggu. Serius.' },
  f1: { tokoh: 'Detektif Red Metcalfe dan timnya di London', tema: ['Obsesi penyidik', 'Simbolisme religius dalam kejahatan', 'Harga psikologis bagi aparat'], tanya: ['Bagaimana pekerjaan gelap memengaruhi kehidupan pribadi penyidik?'], mirip: 'Serial BBC Messiah (2001)', naswa: 'Gelap sekali. Aku bacanya siang hari sambil minum teh talua dari RM Padang.' },
  f2: { tokoh: 'Dimas Suryo (eksil di Paris) · Lintang Utara (putrinya) · Vivienne (ibu Lintang) · Segara Alam', tema: ['Eksil politik & rindu tanah air', 'Identitas anak dari dua dunia', 'Sejarah 1965, Mei 1968, dan Reformasi 1998', 'Makanan sebagai rumah (Restoran Tanah Air)'], tanya: ['Apa arti "pulang" bagi orang yang dilarang pulang?', 'Bagaimana sejarah keluarga membentuk kita?'], mirip: 'Laut Bercerita (Leila S. Chudori), Amba (Laksmi Pamuntjak)', naswa: 'Bagian masak-memasak di restoran Paris bikin aku lapar. Pas banget sekarang ada RM Padang di sebelah rumah!' },
  f3: { tokoh: 'Anna (remaja Norwegia) · Nova (cicitnya di masa depan)', tema: ['Krisis iklim', 'Tanggung jawab antargenerasi', 'Kepunahan spesies'], tanya: ['Apa yang ingin kamu wariskan untuk anak cucu?'], mirip: 'Dunia Sophie (Jostein Gaarder)', naswa: 'Setelah baca ini aku bikin komposter di taman. Kecil, tapi mulai.' },
  f4: { tokoh: 'Alicia Berenson (pelukis) · Theo Faber (psikoterapis) · Gabriel (suami Alicia)', tema: ['Trauma & keheningan', 'Narator yang tidak bisa dipercaya', 'Obsesi dan pengkhianatan', 'Seni sebagai bahasa'], tanya: ['Kapan kamu mulai curiga pada narator?', 'Mengapa lukisan "Alcestis" begitu penting?'], mirip: 'Gone Girl (Gillian Flynn)', naswa: 'Sebagai pelukis, aku merinding: satu lukisan bisa jadi pengakuan paling jujur.' },
  f5: { tokoh: 'Noriko Takaki · lima sahabat SMA-nya', tema: ['Kebenaran tanpa empati', 'Tekanan kelompok', 'Rasa bersalah jangka panjang'], tanya: ['Apakah selalu benar berarti selalu baik?'], mirip: 'Holy Mother (Akiyoshi Rikako)', naswa: 'Aturan itu penting, tapi hati lebih penting. Pelajaran buat Pak RT juga, hihi.' },
  f6: { tokoh: 'Honami (seorang ibu) · para penyidik', tema: ['Cinta ibu yang ekstrem', 'Keadilan vs balas dendam', 'Rasa aman anak-anak'], tanya: ['Di mana batas cinta orang tua?'], mirip: 'Confessions (Kanae Minato)', naswa: 'Twist-nya bikin aku menutup buku lalu menatap langit-langit lama sekali.' },
  f7: { tokoh: 'Owen · Javier · Grace · David · Natalya · Sean · Monroe', tema: ['Warisan leluhur', 'Persahabatan & kepercayaan', 'Ingatan genetik (Animus)'], tanya: ['Kalau bisa menjelajah ingatan leluhur, siapa yang ingin kamu kunjungi?'], mirip: 'Seri Assassin\'s Creed', naswa: 'Handoyo yang pinjam duluan. Katanya lebih seru daripada main game-nya.' },
  f8: { tokoh: 'Saikawa Sōhei (dosen) · Nishinosono Moe (mahasiswi) · Magata Shiki (ilmuwan jenius)', tema: ['Logika & pemrograman', 'Isolasi dan kejeniusan', 'Misteri ruang tertutup'], tanya: ['Apa hubungan judul dengan sistem bilangan heksadesimal?'], mirip: 'Novel "honkaku" Jepang lain seperti karya Soji Shimada', naswa: 'Handoyo menjelaskan heksadesimal tiga kali. Aku tetap pusing, tapi ceritanya keren.' },
  f9: { tokoh: 'Hanio Yamada · para "pembeli" hidupnya', tema: ['Kehampaan hidup modern', 'Absurditas', 'Menemukan alasan untuk hidup'], tanya: ['Mengapa Hanio justru ingin hidup di akhir cerita?'], mirip: 'The Stranger (Albert Camus)', naswa: 'Premisnya kelam, tapi ujungnya tentang memilih hidup. Kalau kamu merasa hampa, cerita ke orang terdekat ya — atau SEJIWA 119 ext 8.', help: true },
  f10: { tokoh: 'Connell Waldron · Marianne Sheridan', tema: ['Cinta yang tak terucap', 'Kelas sosial', 'Kesehatan mental', 'Komunikasi'], tanya: ['Apa yang menghalangi Connell dan Marianne untuk jujur?'], mirip: 'Conversations with Friends (Sally Rooney)', naswa: 'Mereka butuh satu hal: ngobrol! Untung Handoyo cerewet kalau soal perasaan.' },
  f3b: null,
  n1: { tokoh: 'Atlas bergambar per regio tubuh', tema: ['Anatomi umum & sistem gerak', 'Organ dalam', 'Kepala, leher & neuroanatomi'], tanya: ['Tips belajar: pelajari per regio, gambar ulang, dan hubungkan dengan fungsi (fisiologi).'], mirip: 'Netter\'s Atlas of Human Anatomy', naswa: 'Aku pakai atlas ini untuk belajar menggambar figur manusia yang proporsional.' },
  n2: { tokoh: 'Sistem organ: saraf, otot, jantung, paru, ginjal, cerna, hormon', tema: ['Homeostasis sebagai benang merah'], tanya: ['Mengapa tubuh berkeringat saat musim panas di Griya Asri?'], mirip: 'Guyton & Hall Textbook of Medical Physiology', naswa: 'Kak Dinda bilang ini buku wajib zaman kuliah.' },
  n3: { tokoh: 'Robert Axelrod · Anatol Rapoport (pencipta strategi Tit for Tat)', tema: ['Dilema tahanan berulang', '"Bayang-bayang masa depan" membuat kerja sama menguntungkan', 'Gencatan senjata spontan "hidup dan biarkan hidup" di parit Perang Dunia I'], tanya: ['Kenapa bertetangga baik itu strategi yang rasional?'], mirip: 'The Selfish Gene (Richard Dawkins)', naswa: 'Tit for Tat versi Griya Asri: Bang Jefri pinjam, Bang Jefri bayar plus bunga. Adil.' },
  n4: { tokoh: 'Richard Dawkins', tema: ['Efek gen di luar tubuh', 'Bendungan berang-berang & rumah larva ulat kadis', 'Parasit yang mengubah perilaku inang'], tanya: ['Apakah rumah kita termasuk "fenotipe yang diperluas"?'], mirip: 'The Selfish Gene', naswa: 'Kalau begitu, perpustakaan lantai 2 ini fenotipe-ku, hehe.' },
  n5: { tokoh: 'Firdaus · seorang psikiater (narator bingkai)', tema: ['Penindasan terhadap perempuan', 'Martabat & kebebasan', 'Suara yang dibungkam'], tanya: ['Mengapa Firdaus menolak meminta grasi?'], mirip: 'Sastra perempuan Timur Tengah lain karya Nawal El Saadawi', naswa: 'Berat, tapi penting. Setiap perempuan berhak aman dan didengar.' },
  u1: { tokoh: 'Malcolm Gladwell', tema: ['Thin-slicing (keputusan dalam dua detik)', 'Kasus patung kouros Museum Getty', '"Kesalahan Warren Harding": terkecoh penampilan', 'Audisi orkestra di balik tirai'], tanya: ['Kapan intuisimu terbukti benar, dan kapan menipu?'], mirip: 'Thinking, Fast and Slow (Daniel Kahneman)', naswa: 'Kolektor lukisan menilai karyaku dalam hitungan detik. Blink banget!' },
  u2: { tokoh: 'Dale Carnegie', tema: ['Minat yang tulus pada orang lain', 'Mengingat nama', 'Mendengar lebih banyak daripada bicara', 'Menghindari debat yang tak perlu'], tanya: ['Prinsip mana yang paling sulit kamu terapkan?'], mirip: 'The 7 Habits of Highly Effective People', naswa: 'Tips mengingat nama sangat berguna di komplek yang warganya sudah 40 orang lebih.' },
  u3: { tokoh: 'Seorang filsuf & seorang pemuda (dialog lima malam)', tema: ['Teleologi vs etiologi: tujuan, bukan trauma, yang menggerakkan kita', 'Pemisahan tugas', 'Berhenti mencari pengakuan', 'Perasaan komunitas'], tanya: ['Tugas siapa sebenarnya kekhawatiranmu hari ini?'], mirip: 'Berani Bahagia (sekuelnya)', naswa: 'Harga lukisanku bukan tugasku untuk dipikirkan pembeli. Tugasku melukis sebaik mungkin.' },
  u4: { tokoh: 'Farah Qoonita', tema: ['Menerima ujian', 'Mengelola ekspektasi', 'Hidup sebagai perjalanan pulang'], tanya: ['Hal kecil apa yang membuatmu tenang hari ini?'], mirip: 'Buku-buku renungan Islami populer', naswa: 'Cocok dibaca pagi sebelum mulai melukis.' },
  i5: { tokoh: 'Frank Andersen (ilmuwan evolusi) · Ana & José', tema: ['Evolusi & kesadaran', 'Seni dan realitas (lukisan La Maja karya Goya)', 'Makna keberadaan manusia'], tanya: ['Apa hubungan lukisan Goya dengan tokoh Ana?'], mirip: 'Dunia Sophie, Dunia Anna (Jostein Gaarder)', naswa: 'Novel filsafat yang pakai lukisan sebagai kunci — pas sekali untukku.' },
  i6: { tokoh: 'Kakek garin penjaga surau · Ajo Sidi (pembual) · Haji Saleh (tokoh dalam cerita Ajo Sidi)', tema: ['Ibadah vs tanggung jawab sosial', 'Satire keagamaan', 'Kampung yang ditinggalkan'], tanya: ['Mengapa Haji Saleh tetap dianggap bersalah?'], mirip: 'Kumpulan cerpen A.A. Navis lainnya', naswa: 'Uda Rizal di RM Padang sebelah katanya juga suka cerpen ini — sama-sama orang Minang seperti A.A. Navis.' },
  i7: { tokoh: 'Larasati (Ara), bintang film di masa revolusi', tema: ['Perempuan dalam revolusi', 'Oportunisme & pengkhianatan', 'Seni dan propaganda'], tanya: ['Apa pilihan terberat Ara?'], mirip: 'Tetralogi Buru (Pramoedya Ananta Toer)', naswa: 'Ara seniman yang harus memilih berpihak. Seni memang tidak pernah netral.' },
  i8: { tokoh: 'Tim arkeolog internasional · seorang kaligrafer abad pertengahan', tema: ['Seni kaligrafi Islam', 'Pertemuan Timur dan Barat', 'Makna "menemukan"'], tanya: ['Apa yang sebenarnya dicari para arkeolog?'], mirip: 'My Name is Red (Orhan Pamuk)', naswa: 'Aku jadi pengin belajar kaligrafi pakai kuas kaligrafi di studio.' },
  i9: { tokoh: 'Richard Dawkins', tema: ['Gen sebagai replikator', 'Tubuh sebagai "mesin kelangsungan hidup"', 'Strategi stabil evolusioner (ESS)', 'Lahirnya istilah "meme"'], tanya: ['Bagaimana gen "egois" menghasilkan hewan yang altruis?'], mirip: 'The Extended Phenotype', naswa: 'Oyen merawat anak-anak Snowy. Dawkins pasti punya penjelasannya.' },
  i10: { tokoh: 'Keluarga Winaya · Mala (anak jenius)', tema: ['Rahasia keluarga', 'Kondisi kejiwaan', 'Rumah sebagai sumber teror'], tanya: ['Apa yang sebenarnya dilihat Mala?'], mirip: 'Thriller psikologis Indonesia lainnya', naswa: 'Setelah baca, aku cek semua pintu lantai 2 dua kali. Aman!' },
};
function studyPages(S) {
  const pages = [`TOKOH & ISI UTAMA: ${S.tokoh}.`, `TEMA BESAR:\n• ${S.tema.join('\n• ')}`, `PERTANYAAN KLUB BUKU GRIYA ASRI:\n${S.tanya.map((q, i) => `${i + 1}. ${q}`).join('\n')}`, `KALAU SUKA BUKU INI, COBA JUGA: ${S.mirip}.`, `CATATAN NASWA: "${S.naswa}"`];
  return pages;
}
for (const b of BOOKS) {
  const add = PD[b.id] || (STUDY[b.id] ? studyPages(STUDY[b.id]) : null); if (!add) continue;
  const last = b.pages[b.pages.length - 1];
  const hasDisc = typeof last === 'string' && last.startsWith('Halaman ini berisi ringkasan');
  if (hasDisc) b.pages.splice(b.pages.length - 1, 0, ...add); else b.pages.push(...add);
  if (STUDY[b.id] && STUDY[b.id].help) b.help = true;
}
